#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

import shodan
import sys
import os

def logo():
    os.system("clear")
    print("""
       __  __            __               
 #####                                         #####                             
#     # #    #  ####  #####    ##   #    #    #     #  ####   ####  #    # ##### 
#       #    # #    # #    #  #  #  ##   #    #       #    # #    # #    #   #   
 #####  ###### #    # #    # #    # # #  #     #####  #      #    # #    #   #   
      # #    # #    # #    # ###### #  # #          # #      #    # #    #   #   
#     # #    # #    # #    # #    # #   ##    #     # #    # #    # #    #   #   
 #####  #    #  ####  #####  #    # #    #     #####   ####   ####   ####    #     
                                       
    """)

def usage():
    logo()
    print("""
    -----------------
    :::::::TYPE::::::
    -----------------
          shodan-scout full_addr  -->>   Get Information with IP Address
          shodan-scout half_addr    -->>   Get Information of IP Address only

    """)
    
def ip_search():
    Api_Key=str(input("Enter Your Shodan API Key: "))
    List_Search=str(input("Enter Shodan Search: "))
    api = shodan.Shodan(Api_Key)
    try:
        results = api.search(List_Search)
        print ("Found Your Search: %s" %results['total'])
        for results in results['matches']:
            print ("IPs Found: %s" %result['ip_str'])
            print (results['data'])
            print ("")
    except shodan.APIERROR as e:
        print ("Error Occured :: %s" %e)

def api_search():
    Api_Key=str(input("Enter Your Shodan API Key: "))
    List_Search=str(input("Enter Shodan Search: "))
    api = shodan.Shodan(Api_Key)
    try:
        results = api.search(List_Search)
        for results in results['matches']:
            print ("%s" %results['ip_str'])
    except:
        print ("Occured Error :: %s" % e)

def main() :    
    arg = sys.argv[1:]

    if len(arg)!=1:
        usage()
    elif sys.argv[1] == "full_addr":
        logo()
        api_search()
    elif sys.argv[1] == "half_addr":
        logo()
        ip_search()
    else:
        usage()

        
if __name__ == '__main__' :
    main()
